question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Bulls are attracted to the color red.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
     "question": "AMC&#039;s 'The Walking Dead', Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in Season 1.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "The Xenomorph from the science fiction film 'Alien' has acidic blood.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "The Korean War ended in 1953 without any ceasefire.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The title of the 1969 film 'Krakatoa, East_of Java' is incorrect, as Krakatoa is in fact west of Java.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "There is an island in Japan called \u014ckunoshima, A.K.A. 'Rabbit Island', so named because of it&#039;s huge population of rabbits.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The longest place named in the United States is Lake Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The ultimate phrase used by Pharah from Overwatch is: 'Justice rains from above!'",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Super Mario Bros. was released in 1990.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Politics",
     "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "History",
     "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more powerful and symmetrical.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Shang Tsung is a playable character in Mortal Kombat XL.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "All of these maps were in 'Tom Clancy&#039;s Rainbow Six Siege' on its initial release: House, Clubhouse, Border, Consulate.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "Ferrari has never made a V10 engine for any of its cars.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Joan Cusack starred in the 2009 disaster movie, '2012'.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In 'Super Mario World', the rhino mini-boss, Reznor, is named after the lead singer of the band 'Nine Inch Nails'.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "The song 'Mystery Train' was released by artist 'Little Junior&#039;s Blue Flames' in 1953.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
     "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The HTML5 standard was published in 2014.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Studio Ghibli is a Japanese animation studio responsible for the films 'Wolf Children' and 'The Boy and the Beast'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The game 'Battlefield 1' takes place during World War I.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
     "question": "The book 1984 was published in 1949.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Celebrities",
     "question": "Marilyn Monroe was born on July 1, 1926.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The United States of America was the first country to launch a man into space.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "If you grab the bladed end of a longsword in a specific way, you will not cut yourself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Comics",
     "question": "The 'Pepe' meme originated from a comic drawn by Matt Furie called 'Boy&#039;s Club'?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "The Ace Attorney trilogy was suppose to end with 'Phoenix Wright: Ace Attorney &minus; Trials and Tribulations' as its final game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
     "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In Portal, the Companion Cube&#039;s ARE sentient.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "A pasodoble is a type of Italian pasta sauce.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "EDM label Monstercat signs tracks instead of artists.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Android versions are named in alphabetical order.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Politics",
     "question": "Nazi Germany surrendered on Harry Truman&#039;s birthday while he was president.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
     "question": "The set of all algebraic numbers is countable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Rhode Island is actually located on the US mainland, despite its name.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the game 'Subnautica', a 'Spadefish' will attack you.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals", "question": "Rabbits are rodents.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "Antarctica is the largest desert in the world.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In 'JoJo&#039;s Bizarre Adventure', Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
